### ISSUE TITLE
Incorrect display of status

### ISSUE THREAD

**Issue by Vaszago** [LavermanJJ/home-assistant-solarfocus#103]
In HA, the status of HK1 when the outside switch-off temperature is reached indicates that the outside cooling switch-off temperature has been reached. Which is true. It should actually just say switch-off temperature reached. It's just cosmetic but maybe you can take a look at it.

<img width="414" alt="image" src="https://github.com/LavermanJJ/home-assistant-solarfocus/assets/66181893/64f88bef-a188-4d16-8159-c4dfa0377863">

**Comment by Vaszago** [comment]
<img width="758" alt="image" src="https://github.com/LavermanJJ/home-assistant-solarfocus/assets/66181893/98449d72-d7d1-4f17-951d-712244a27d4f">


With HK2 the display is correct

**Comment by LavermanJJ** [comment]
Solarfocus provides different states for reaching the the threshold: 
* `9` for "Außenabschalttemperatur Heizbetrieb erreicht"
* `27` for "Außenabschalttemperatur Absenkbetrieb erreicht"
* `30` for "Außenabschalttemperatur Kühlen erreicht"

So depending on what the current mode of the heating circuit is, the respective state is shown. In your example, I assume HK1 is set to cooling, and HK2 isn't. 
Hence, I'd close this issue as it seems to work as expected. Please re-open and comment if you think otherwise.
