### ISSUE TITLE
Add support for eco top light

### ISSUE THREAD

**Issue by LavermanJJ** [LavermanJJ/home-assistant-solarfocus#48]
The door contact binary_sensor is inverted for the eco top light. 

```
SolarfocusBinarySensorEntityDescription(
         key="door_contact",
         device_class=BinarySensorDeviceClass.DOOR,
         on_state="0", # might be one for terminator, but is 0 for eco top light 
```

Are there further differences?

**Comment by lein1013** [comment]
Till, now I just saw this issue.
I've requested the solarfocus support, that they provide some more public available documents, we could use.

**Comment by tinerop** [comment]
Here is a report on what works with the Ecotop Light - and few things I'm not entirely sure of...

I use a Solarfocus "**Ecotop light"** with Firmware Version V 22.050 in combination with a „Hygiene Kombispecher HYKO“ (thats a buffer with an integrated freshwater-compartment).

Using your amazing HACS-integration version 2.2.2 / Home Assistant 2023.4.4 / Supervisor 2023.04.0 / Operating System 9.5 / Frontend 20230411.1 - latest.


**Controls "Steuerelemente"**  (no issues found, same as in your screenshot)

**Configuration "Konfiguration"** - (no issues found, same as in your screenshot)

**Sensors "Sensoren":**

**Biomass Boiler (Pelletsheizung, Brenner)**
Biomass boiler ash container: "23%" (correct)
Biomass boiler cleaning: "-1%" (not sure what that means?)
Biomass boiler door contact: "closed" (correct)
Biomass boiler log wood: "nachlegen nicht notwendig" (correct - since it's pellets only)
Biomass boiler message number: "0" (correct)
Biomass boiler octoplus buffer temperature bottom "270.0 C" (not sure what that means? guess "octoplus" can be removed)
Biomass boiler octoplus buffer temperature top "0.0 C" (not sure what that means? guess "octoplus" can be removed)
Biomass boiler outdoor temperature: "10.2 C" (correct)
Biomass boiler temperature "66.0 C" (correct)

**Boiler 1 (freshwater-compartment within „Buffer1“)**
Boiler 1 circulation: „gesperrt“ (seems correct, - guess thats for the circulation pump?)
Boiler 1 mode: „immer ein“ (correct)
Boiler 1 single charge: „0“ (seems correct, guess this means off?)
Boiler 1 state: „Bereitschaft“ (correct)
Boiler 1 temperature: „65,3 C“ (correct)

**Buffer 1 (buffer with an integrated freshwater-compartment here „Boiler 1“)**
Buffer 1 bottom temperature: „64,4 C“ (correct)
Buffer 1 mode: „immer aus“ (not sure why its "always off"?)
Buffer 1 pump: „läuft“ (guess it’s the other way round, should be „läuft nicht“ since nothing pumps at the moment guess this is when the furnace pumps water in the buffer?)
Buffer 1 state: „Bereitschaft“ (correct)
Buffer 1 top temperature: „65,2 C“ (correct)

**Heating Circuit 1 (Heizkreis 1)**
Heating circuit 1 circulator pump: „läuft nicht“ (correct)
Heating circuit 1 humidity: „-0,1%“(not sure what that means?)
Heating circuit 1 limit thermostat „OK“ (not sure what that means?)
Heating circuit 1 mixer valve: „0%“ (correct)
Heating circuit 1 room temperature: „124,1 C“ (correct, - guess because I have no room thermostat)
Heating circuit 1 state: „Außenabschalttemperatur Absenkbetrieb erreicht“ (correct)
heating_circuit_1_supply_temperature: 29,5 C“ (correct)


I guess the following sensors can be deleted, they are depreciated since the last update 2.2.2 and still in from my initial installation...
Biomass boiler boiler operating mode – this entity is no longer provided by solarfocus
Biomass boiler status – this entity is no longer provided by solarfocus

I really appreciate your amazing  integration!
Thanks for your work!
