### ISSUE TITLE
Heizkreise werden nur in Fahrenheit und nicht in Celsius dargestellt

### ISSUE THREAD

**Issue by wenz42** [LavermanJJ/home-assistant-solarfocus#97]
Hi Laverman,

Thank you very mich for This addon.

I am using it with Solarfocus Pellet Elegance and it is working well.

the only issue I have is the uom of sensor: climate.solarfocus_heating_circuit_2_thermostat

it is only showing the temperature in Fahrenheit and not in Celsius.

All other sensors are in Celsius.

I am not able to change it.

any Ideas?

Thank you

BR

Wenz 
<img width="378" alt="Solarfocus HA Dashboard" src="https://github.com/LavermanJJ/home-assistant-solarfocus/assets/158784532/8d3e5d94-2faa-4cb1-8ed6-6c196e34ae58">

<img width="579" alt="Vorlauf Temperatur 1" src="https://github.com/LavermanJJ/home-assistant-solarfocus/assets/158784532/05303c2c-2b1a-46e4-9876-6297c1d92995">

**Comment by LavermanJJ** [comment]
That's very strange, because in https://github.com/LavermanJJ/home-assistant-solarfocus/blob/e2c61c5bf4510f6b6b18f607080f4cadad3e6a06/custom_components/solarfocus/climate.py#L199 is returns Celsius as unit of measurement. Do you have other entities from the climate domain (climate.*)? If so, do they show Celsius or Fahrenheit?

**Comment by wenz42** [comment]
Hi Laverman,

unfortunately both climate.xxx show Fahrenheit.

I am not able to change UOM.

But with all other sensors, I was able to change the UOM for example sensor.solarfocus_biomass_boile_outdoor_temperature.

Why it is not possible to change UOM manually on climate.xxx sensors?

thank you

br

Wenz
